# -*- coding: utf-8 -*-
"""Simple To-Do List Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJmkLIhQWf5TBh1DMbSY5SEyAWX0u1rf
"""

tasks = []

def add_task():
  task = input("Enter the task: ")
  tasks.append(task)
  print(f"'{task}' has been added to your to-do list!")

def view_task():
  if len(tasks) == 0:
    print("Your to-do list is empty.")
  else:
    print("/nYour to-do list:")
    for i in range(len(tasks)):
      print(f"{i+1}. {tasks[i]}")

def remove_task():
    view_task()
    if len(tasks) == 0:
        return
    task_num = input("Enter the task number to remove: ")
    task_num = int(task_num) - 1
    if 0 <= task_num < len(tasks):
        removed = tasks.pop(task_num)
        print(f"'{removed}' has been removed!")
    else:
        print("Invalid number or out of range!")


while True:
  print("To-Do List Manager")
  print("1. Add Task")
  print("2. View Task")
  print("3. Remove Task")
  print("4. Exit")

  user = input("Enter your choice (1-4): ")

  if user == "1":
    add_task()
  elif user == "2":
    view_task()
  elif user == "3":
    remove_task()
  elif user == "4":
    print("Good Bye!")
    break

tasks = ["Buy groceries", "Walk dog", "Read book"]
# python see     0               1           2
# user see       1               2           3